flask:
    container_name: ${NOME_PROJETO}_flask
    build: ./
    volumes:
        - "${APP}:/app"
    ports:
         - "${PORTA}:8080"
    command: sh -c "service nginx start && gunicorn --workers 3 --bind unix:/app/app.sock -m 777 wsgi:app && nginx -s reload"
