version: '3.1'

services:
    node:
        container_name: node
        build:
            context: ./
            dockerfile: Dockerfile-node
        volumes:
            - ./app:/project/app
        command: >
            sh -c "ls -lah /project/app/static
            && npm --prefix /project/app/static install /project/app/static "

    nginx:
        container_name: nginx
        image: nginx:1.15
        volumes:
            - ./:/var/www
            - ./app.conf:/etc/nginx/conf.d/default.conf
        ports:
            - ${PORTA}:80
        networks:
            - my-network
        depends_on:
            - flask

    flask:
        container_name: flask
        build:
            context: ./
            dockerfile: Dockerfile
        command: gunicorn --workers 4 --bind 0.0.0.0:8000 "app.app:create_app()"
        volumes:
            - ./:/var/www
        networks:
            my-network:
                aliases:
                    - flask-app

networks:
    my-network:
